/**
 * The guided lessons shown in the coach panel. Each lesson has a goal, steps,
 * a starting workspace (or null to build on the previous one) and a check.
 */
import type { BlockState, Lesson, WorkspaceState } from '../types.ts';

/** A workspace with one empty device, optionally with extra settings. */
const dev = (extra: Partial<BlockState> = {}): WorkspaceState => ({
  blocks: { languageVersion: 0, blocks: [{ type: 'verse_device', x: 30, y: 30, fields: { NAME: 'my_device' }, ...extra }] },
});

export const LESSONS: Lesson[] = [
    { title: 'Hello, Verse', concept: 'OnBegin and Print',
      goal: 'Make the device print "Hello, world!" when the game starts.',
      steps: ['Open Text and drag a print block into the OnBegin slot.', 'Click the text inside it and type Hello, world!', 'Switch to Text view to see the Verse you wrote.'],
      check: (c) => /OnBegin[\s\S]*Print\("Hello, world!"\)/.test(c), start: dev() },
    { title: 'Take a breath', concept: 'Sleep and <suspends>',
      goal: 'Print "Ready", wait 3 seconds, then print "Go!".',
      steps: ['Put print "Ready" in OnBegin.', 'Add a wait block from Time and set it to 3.', 'Add print "Go!" after it.', 'Notice the code says Sleep(3.0): Sleep wants a float.'],
      check: (c) => /Print\("Ready"\)\s*\n\s*Sleep\(3\.0\)\s*\n\s*Print\("Go!"\)/.test(c), start: dev() },
    { title: 'Count it out', concept: 'for loops and string interpolation',
      goal: 'Print "Round 1" through "Round 5".',
      steps: ['Drag "for I := 1..5" from Loops into OnBegin.', 'Put a print inside, and plug "text with a value" into it.', 'Set the label to Round and the value name to I.'],
      check: (c) => /for \(I := 1\.\.5\):\s*\n\s*Print\("Round ?\{I\}"\)/.test(c), start: dev() },
    { title: 'Wire up a button', concept: '@editable, events, and handlers',
      goal: 'When a player presses MyButton, print "Pressed!".',
      steps: ['Add an @editable button_device named MyButton to linked devices.', 'Add a "when called OnButtonPressed receives agent" block to functions & handlers, with a print inside.', 'In OnBegin, add "when MyButton InteractedWithEvent run OnButtonPressed".', 'In UEFN: build, place the device, and link MyButton in Details.'],
      check: (c) => /MyButton:button_device/.test(c) && /MyButton\.InteractedWithEvent\.Subscribe\(OnButtonPressed\)/.test(c) && /OnButtonPressed\(Agent:agent\):void\s*=\s*\n\s*Print\(/.test(c), start: dev() },
    { title: 'Loot button', concept: 'Calling device functions with Agent',
      goal: 'Pressing the button gives that player an item from MyGranter.',
      steps: ['Keep your button from lesson 4.', 'Add an @editable item_granter_device named MyGranter.', 'Inside OnButtonPressed, add "MyGranter . GrantItem(Agent)".'],
      check: (c) => /MyGranter:item_granter_device/.test(c) && /OnButtonPressed\(Agent:agent\)[\s\S]*MyGranter\.GrantItem\(Agent\)/.test(c), start: null },
    { title: 'Three strikes', concept: 'var, set, and if',
      goal: 'Only grant the item on the 3rd press or later.',
      steps: ['Add "var Presses : int = 0" to linked devices & variables.', 'In the handler: set Presses += 1.', 'Wrap GrantItem in "if Presses >= 3".'],
      check: (c) => /var Presses:int = 0/.test(c) && /set Presses \+= 1/.test(c) && /if \(Presses >= 3\):\s*\n\s*MyGranter\.GrantItem\(Agent\)/.test(c), start: null },
    { title: 'Danger zone', concept: 'Failable calls: GetFortCharacter[]',
      goal: 'Anyone entering MyZone takes 25 damage.',
      steps: ['Add an @editable mutator_zone_device named MyZone.', 'Make a handler OnEnter that receives agent.', 'Inside: "if Agent has a character", then FortChar.Damage 25.', 'Subscribe MyZone AgentEntersEvent to OnEnter in OnBegin.'],
      check: (c) => /MyZone\.AgentEntersEvent\.Subscribe\(OnEnter\)/.test(c) && /if \(FortChar := Agent\.GetFortCharacter\[\]\):\s*\n\s*FortChar\.Damage\(25\.0\)/.test(c), start: dev() },
    { title: 'Maybe a player', concept: 'Options: ?agent',
      goal: 'A trigger prints "Triggered by a player" only when a real player set it off.',
      steps: ['Add @editable trigger_device MyTrigger.', 'Handler OnTriggered receives "maybe agent (?agent)".', 'Inside: "if there is an agent", then print.', 'Subscribe MyTrigger TriggeredEvent to OnTriggered.'],
      check: (c) => /OnTriggered\(MaybeAgent:\?agent\)/.test(c) && /if \(Agent := MaybeAgent\?\):\s*\n\s*Print\(/.test(c) && /MyTrigger\.TriggeredEvent\.Subscribe\(OnTriggered\)/.test(c), start: dev() },
    { title: 'Target timer', concept: 'spawn, loops, and random',
      goal: 'Aim-trainer style: a <suspends> function loops forever, printing a random target number every 2 seconds.',
      steps: ['Make a function SpawnTargets with <suspends> ticked.', 'Inside: loop forever → print "Target {random int 1 to 8}" → wait 2.', 'In OnBegin, spawn SpawnTargets.'],
      check: (c) => /SpawnTargets\(\)<suspends>:void\s*=/.test(c) && /loop:/.test(c) && /GetRandomInt\(/.test(c) && /spawn\{SpawnTargets\(\)\}/.test(c), start: dev() },
    { title: 'Open the toolbox', concept: 'using and modules',
      goal: 'Auto-using is off. Add the using lines this code needs so every warning clears.',
      steps: ['Read "Needs fixing": each message names a function and the module it lives in.', 'Open the Using category and drag the right using blocks into the device\'s using slot.', 'Watch the text view: the using line appears the moment you snap the block in.', 'Tip: the fix buttons can do it for you, but try it by hand first.'],
      check: (c, r) => !!r && !r.autoUsing && !r.warnings.some(w => w.level === 'error') && /using \{ \/Verse\.org\/Random \}/.test(c) && /using \{ \/UnrealEngine\.com\/Temporary\/Diagnostics \}/.test(c) && /using \{ \/Fortnite\.com\/Devices \}/.test(c),
      start: { blocks: { languageVersion: 0, blocks: [{ type: 'verse_device', x: 30, y: 30, fields: { NAME: 'my_device', AUTO: false }, inputs: { ONBEGIN: { block: { type: 'verse_print', inputs: { TEXT: { block: { type: 'verse_text_join', fields: { LABEL: 'Lucky number: ' }, inputs: { V: { block: { type: 'verse_random', fields: { LO: 1, HI: 100 } } } } } } } } } } }] } } },
    { title: 'Moving parts', concept: 'Events that send nothing',
      goal: 'Start a prop mover called Door when the game begins, and print "Door arrived" when it finishes.',
      steps: ['Add @editable prop_mover_device named Door.', 'In OnBegin, use "Door . Begin()".', 'Make a handler OnDoorFinished that receives nothing. FinishedEvent sends no agent.', 'Subscribe Door FinishedEvent to OnDoorFinished, and print inside the handler.'],
      check: (c) => /Door:prop_mover_device/.test(c) && /Door\.Begin\(\)/.test(c) && /Door\.FinishedEvent\.Subscribe\(OnDoorFinished\)/.test(c) && /OnDoorFinished\(\):void\s*=\s*\n\s*Print\("Door arrived"\)/.test(c), start: dev() },
  { title: 'Lists of things', concept: 'Arrays and for each',
    goal: 'Keep a list of scores, add one more, and print every score.',
    steps: ['Open Lists & Maps. Drag the array block into linked devices & variables: var Scores : []int = array{3, 5, 8}.',
      'In OnBegin, "add to Scores" the number 13.',
      'Add "for each Item in Scores" and print Item inside it.',
      'Try ticking "with position/key" to also get each position (it starts at 0).'],
    check: (c) => /var Scores:\[\]int = array\{3, 5, 8\}/.test(c) && /set Scores \+= array\{13\}/.test(c) && /for \((\w+ -> )?\w+ : Scores\):/.test(c),
    start: dev() },
  { title: 'Score every player', concept: 'Maps and "if it exists"',
    goal: 'Each press of MyButton adds 1 to that player\'s own score, stored in a map.',
    steps: ['Link a button_device named MyButton, and add var PlayerScores : [agent]int = map{}.',
      'Make a handler OnPressed that receives an agent, and subscribe the button to it.',
      'Inside: "if Score := PlayerScores[Agent]" then set PlayerScores[Agent] = Score + 1.',
      'In its else part: set PlayerScores[Agent] = 1 (their first point).'],
    check: (c) => /PlayerScores:\[agent\]int = map\{\}/.test(c) && /if \(\w+ := PlayerScores\[Agent\]\):/.test(c) && /set PlayerScores\[Agent\] = \w+ \+ 1/.test(c) && /else:\n\s+if \(set PlayerScores\[Agent\] = 1\)/.test(c),
    start: dev() },
  { title: 'Maybe a winner', concept: 'Options',
    goal: 'The first player to press MyButton becomes the Winner; print a message when there is one.',
    steps: ['Link MyButton and add var Winner : ?agent = false (empty).',
      'In the handler: "if W := value in Winner?" … else: set Winner = option{Agent}.',
      'Print something inside the then part, like "We already have a winner".'],
    check: (c) => /var Winner:\?agent = false/.test(c) && /set Winner = option\{Agent\}/.test(c) && /if \(\w+ := Winner\?\):/.test(c),
    start: dev() },
  { title: 'Functions that answer', concept: 'Inputs, results and <decides>',
    goal: 'Write Double(X:int):int, and a failable IsHighScore(Score:int) that succeeds at 10 or more. Use both.',
    steps: ['From Functions, use the Double preset: its last line (check / result) is X * 2, so that is what it gives back.',
      'Use the IsHighScore preset: tick <decides>, and make its line Score >= 10.',
      'In OnBegin: print the result of Double(21), and "if try IsHighScore[12]" print "High score!".'],
    check: (c) => /Double\(X:int\):int\s*=\n\s+X \* 2/.test(c) && /IsHighScore\(Score:int\)<decides><transacts>:void\s*=\n\s+Score >= 10/.test(c) && /Double\(\d+\)/.test(c) && /if \(IsHighScore\[\w+\]\):/.test(c),
    start: dev() },
  { title: 'Your own class', concept: 'Classes, objects and methods',
    goal: 'Make a pet class with a Name and an Age, give it a Birthday() method, then give your pet a birthday in OnBegin.',
    steps: ['From Types, drag the pet class out next to your device (not inside it).',
      'Add a function to its fields & methods: Birthday, with "set Age += 1" inside.',
      'In your device, add a field: var MyPet : pet = pet{Name := "Scout"}.',
      'In OnBegin, "call a method": MyPet . Birthday(), then print MyPet.Age.'],
    check: (c) => /pet := class:/.test(c) && /Name(<\w+>)?:string/.test(c) && /var Age(<\w+>)?:int = 0/.test(c) && /Birthday(<\w+>)?\(\):void =\n\s+set Age \+= 1/.test(c) && /var MyPet:pet = pet\{Name := "Scout"\}/.test(c) && /MyPet\.Birthday\(\)/.test(c),
    start: dev() },
  { title: 'Game states', concept: 'Enums',
    goal: 'Make game_state := enum{Waiting, Playing, Over}, start in Waiting, switch to Playing in OnBegin, and print when it is Playing.',
    steps: ['From Types, drag the enum out next to your device.',
      'In your device: var State : game_state = game_state.Waiting.',
      'In OnBegin: set State = game_state.Playing (use the enum value block).',
      'Then: if State = game_state.Playing, print "Playing!".'],
    check: (c) => /game_state := enum\{Waiting, Playing, Over\}/.test(c) && /var State:game_state = game_state\.Waiting/.test(c) && /set State = game_state\.Playing/.test(c) && /if \(State = game_state\.Playing\):/.test(c),
    start: dev() },
  // ---- Phase 5.1: players & teams ----
  { title: 'Welcome, everyone', concept: 'Players joining (PlayerAddedEvent)',
    goal: 'Print "Welcome!" every time a player joins the game.',
    steps: ['From Events, drag "when the game . PlayerAddedEvent() run OnPlayerAdded" into OnBegin.',
      'Add the handler "when called OnPlayerAdded receives player (Player)" under functions & event handlers.',
      'Put a print "Welcome!" inside it.',
      'Notice the handler receives a player, because that is what PlayerAddedEvent sends.'],
    check: (c) => /GetPlayspace\(\)\.PlayerAddedEvent\(\)\.Subscribe\(OnPlayerAdded\)/.test(c) && /OnPlayerAdded\(Player:player\):void =\n\s+Print\("Welcome!"\)/.test(c),
    start: dev() },
  { title: 'Pick a side', concept: 'Teams and "if it exists"',
    goal: 'When a player presses MyButton, print "You have a team!" only if they are on a team.',
    steps: ['Link a button_device named MyButton, make a handler OnPressed that receives an agent, and subscribe the button to it.',
      'From Teams, drag "team of … in the teams" into an "if it exists" block inside the handler, and name it MyTeam.',
      'Plug the Agent value into its player slot.',
      'Print "You have a team!" inside. GetTeam can fail (a player might have no team), which is why it needs the if.'],
    check: (c) => /MyButton\.InteractedWithEvent\.Subscribe\(OnPressed\)/.test(c) && /if \(\w+ := GetPlayspace\(\)\.GetTeamCollection\(\)\.GetTeam\[Agent\]\):\n\s+Print\("You have a team!"\)/.test(c),
    start: dev() },
  { title: 'Knockouts', concept: 'Elimination events and results',
    goal: 'Count every elimination in var Knockouts and print the total each time.',
    steps: ['Add var Knockouts : int = 0 to linked devices & variables.',
      'Subscribe the game\'s PlayerAddedEvent to OnPlayerAdded (receives player).',
      'Inside it: "if Player has a character", then "when FortChar . EliminatedEvent() run OnEliminated".',
      'Make OnEliminated receive "elimination (Result)": set Knockouts += 1, then print "Knockouts: {Knockouts}".'],
    check: (c) => /FortChar\.EliminatedEvent\(\)\.Subscribe\(OnEliminated\)/.test(c) && /OnEliminated\(Result:elimination_result\):void =/.test(c) && /set Knockouts \+= 1/.test(c),
    start: dev() },
];
